# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/manus/manus.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto

# from .. import math as _math__


@dataclass(eq=False, repr=False)
class Scalard(betterproto.Message):
    val: float = betterproto.double_field(1)


@dataclass(eq=False, repr=False)
class Scalarf(betterproto.Message):
    val: float = betterproto.float_field(1)


@dataclass(eq=False, repr=False)
class Vector3D(betterproto.Message):
    x: float = betterproto.double_field(1)
    y: float = betterproto.double_field(2)
    z: float = betterproto.double_field(3)


@dataclass(eq=False, repr=False)
class Quaterniond(betterproto.Message):
    x: float = betterproto.double_field(1)
    y: float = betterproto.double_field(2)
    z: float = betterproto.double_field(3)
    w: float = betterproto.double_field(4)


@dataclass(eq=False, repr=False)
class Pose2D(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
    yaw: float = betterproto.float_field(3)


class ManusHandType(betterproto.Enum):
    UNKNOWN = 0
    LEFT = 1
    RIGHT = 2


@dataclass(eq=False, repr=False)
class ManusHandData(betterproto.Message):
    index: int = betterproto.int32_field(1)
    timestamp: int = betterproto.int64_field(2)
    hand: "ManusHandType" = betterproto.enum_field(3)
    rotations: List["Vector3D"] = betterproto.message_field(4)
    positions: List["Vector3D"] = betterproto.message_field(5)
    quaternions: List["Quaterniond"] = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class ManusTrackerData(betterproto.Message):
    index: int = betterproto.int32_field(1)
    timestamp: int = betterproto.int64_field(2)
    id: int = betterproto.int32_field(3)
    quality: int = betterproto.int32_field(4)
    positions: "Vector3D" = betterproto.message_field(5)
    quaternions: "Quaterniond" = betterproto.message_field(6)
